### ISSUE TITLE
Add detection logic for the Next.js plugin

### ISSUE THREAD

**Issue by ehmicky** [netlify/framework-info#109]
Related: https://github.com/netlify/pod-the-builder/issues/121

The Next.js plugin has some pretty intricate logic to decide whether it can be used or not (see [details here](https://github.com/netlify/pod-the-builder/issues/121#issuecomment-742005603)).

Some of this logic is currently absent from `@netlify/framework-info` which means the UI might be automatically installing the Next.js plugin even though it cannot be used. This would result in failed builds for some new Next.js sites.

**Comment by erezrokah** [comment]
This might a challenge to resolve this and keep the library browser compatible:
https://github.com/netlify/netlify-plugin-nextjs/blob/73cc847947a58150d57f1d44d939e2ff25fda2a8/index.js#L57
