### ISSUE TITLE
Feature: return strategies to known when framework dev server is ready

### ISSUE THREAD

**Issue by erezrokah** [netlify/framework-info#122]
Related to https://github.com/netlify/cli/pull/1817

When detecting the dev command and port, we should also provide a list of polling strategies to know when the framework dev server is ready.

The CLI uses `waitPort` and `HEAD` requests to detect when the server is ready, but for `Next.js` that doesn't work very well so we only use `waitPort`.

cc @eduardoboucas 

A future improvement can be to add an `stdOut` strategy where the caller starts the framework dev server and looks for a specific pattern in the command output.

**Comment by eduardoboucas** [comment]
Sounds great! Thanks for raising this. 🙌🏻
