### ISSUE TITLE
Drop support for Node 8

### ISSUE THREAD

**Issue by ehmicky** [netlify/framework-info#251]
Is there anything that prevents us from dropping support for Node 8 in this repository?
`@netlify/build` and `@netlify/config` are not directly using this repository.

See also https://github.com/netlify/team-dev/issues/2 and https://github.com/netlify/pod-workflow/issues/196

**Comment by erezrokah** [comment]
`build-info` uses it in `buildbot`. If `buildbot` always uses the default Node.js version (12) we can even drop support for Node.js 10.

**Comment by ehmicky** [comment]
`framework-info` is used by Netlify CLI though, which requires Node.js 10, isn't it?

**Comment by erezrokah** [comment]
> `framework-info` is used by Netlify CLI though, which requires Node.js 10, isn't it?

You're correct, we can only drop Node.js 8 support.
