### ISSUE TITLE
feature: install netlify-plugin-gatsby for any gatsby sites

### ISSUE THREAD

**Issue by lukeocodes** [netlify/framework-info#296]
**Which problem is this feature request solving?**

We have a new plugin [netlify/netlify-plugin-gatsby](https://github.com/netlify/netlify-plugin-gatsby/) and it should auto install when setting up a new gatsby site

**Describe the solution you'd like**

Add plugin to gatsby framework config

**Describe alternatives you've considered**

**Can you submit a pull request?**

Yes/No.

**Comment by erezrokah** [comment]
See Next.js example https://github.com/netlify/framework-info/blob/5b200490865b001dd71bd824819d20e2a142266b/src/frameworks/next.json#L23
