### ISSUE TITLE
Feature: make this library browser compatible 

### ISSUE THREAD

**Issue by erezrokah** [netlify/framework-info#44]
**Which problem is this feature request solving?**

We would like to be able to use this library from the Browser.
This is currently not possible since it uses Node.js specific APIs:
https://github.com/netlify/framework-info/blob/bbd04b18130018109ba9c435efb59b98c0bab772/src/options.js#L4
https://github.com/netlify/framework-info/blob/bbd04b18130018109ba9c435efb59b98c0bab772/src/detect.js#L41
https://github.com/netlify/framework-info/blob/bbd04b18130018109ba9c435efb59b98c0bab772/src/package.js#L20
https://github.com/netlify/framework-info/blob/bbd04b18130018109ba9c435efb59b98c0bab772/src/run_script.js#L7

**Describe the solution you'd like**

Ability to run the detection from the Browser - `fs` related operations can be refactored to accepts files lists/operations from the caller.

**Describe alternatives you've considered**

Duplicate the logic in another codebase

**Can you submit a pull request?**

Yes

**Comment by ehmicky** [comment]
Background at https://github.com/netlify/pod-the-builder/issues/121 (discussion still ongoing)
