### ISSUE TITLE
 Upgrade minimal Node.js version to Node 12

### ISSUE THREAD

**Issue by ehmicky** [netlify/framework-info#450]
See background at https://github.com/netlify/team-dev/issues/34

We should upgrade the minimal Node.js version to Node `>=12.20.0` and make a major release.

At the moment, `framework-info` is only used by:
  - `build-info`: so support for Node 10 should be dropped first in `build-info`: https://github.com/netlify/build-info/issues/180
  - `netlify-cli`: same thing for Netlify CLI: https://github.com/netlify/cli/issues/3512
  - `netlify-react-ui`: I believe `framework-info` is imported from the browser, using the browser-specific code, so Node.js support should be irrelevant. @nasivuela Could you please confirm this is correct? Thanks!

**Comment by nasivuela** [comment]
> netlify-react-ui: I believe framework-info is imported from the browser, using the browser-specific code, so Node.js support should be irrelevant. @nasivuela Could you please confirm this is correct? Thanks!

Sounds reasonable to me :)

**Comment by ehmicky** [comment]
Done at https://github.com/netlify/framework-info/pull/571
