### ISSUE TITLE
Feature: provide default implementations of browser contexts

### ISSUE THREAD

**Issue by erezrokah** [netlify/framework-info#68]
See conversation [here](https://github.com/netlify/framework-info/pull/58#discussion_r544393449).

Following [this PR](https://github.com/netlify/framework-info/pull/58), browser consumers would need to provide a `context` with the content of `package.json` and a `pathExists` function.

We could potentially simplify this by providing a provider name (e.g. GitHub), a token and a repo and have this library handle getting `package.json` and implementing  `pathExists`. We might need to also provide an API url (for GitHub enterprise).

This can be implemented in this library, or in a separate one (I personally think it belongs in a separate one).

**Comment by MarcL** [comment]
Can we close this @netlify/ecosystem-pod-frameworks? Looks like #58 fixes this.

**Comment by orinokai** [comment]
As far as i understand it, this issue is a follow up improvement to #58, but obviously not a priority since it's been so long. I'd vote to close it for now.
