### ISSUE TITLE
Add SolidJS framework configuration

### ISSUE THREAD

**Issue by nickytonline** [netlify/framework-info#807]
**Which problem is this feature request solving?**

We currently detect Solid Start, but not Solid JS

**Describe the solution you'd like**

Currently we only have a configuration for Solid Start. See https://github.com/netlify/framework-info/blob/main/src/frameworks/solid-start.json.

We'd need to add a solid-js.json configuration for SolidJS.

We’d need to do is look for `the solid-js` npm dependency and have `solid-start` in the excluded npm dependencies for a “vanilla” SolidJS app.

e.g.

```json
{
  "id": "solid-js",
  "name": "SolidJS",
  "category": "static_site_generator",
  "detect": {
    "npmDependencies": ["solid-js"],
    "excludedNpmDependencies": ["solid-start"],
    "configFiles": []
  },
  "dev": {
    "command": "nom run dev",
    "port": 3000,
    "pollingStrategies": [{ "name": "TCP" }]
  },
  "build": {
    "command": "npm run build",
    "directory": "netlify"
  },
  "logo": {
    "default": "/logos/solid-js/default.svg",
    "light": "/logos/solid-js/default.svg",
    "dark": "/logos/solid-js/default.svg"
  },
  "env": {},
  "plugins": []
}
```

We'd also need SolidJS logos.

**And we’d need to exclude the solid-js dependency from the vite framework info.**

**Describe alternatives you've considered**

N/A

**Can you submit a pull request?**

Yes

**Comment by osaf96** [comment]
@nickytonline Hi i would love to help in this. But i'm a bit in doubt if i can do  this or not. is it good first issue? Can you guide me a bit
